[build]
target = "i686-unknown-linux-gnu"
rustflags = [
    "-C", "link-arg=-Tboot/linker.ld",
    "-C", "link-arg=-no-pie",
    "-C", "linker-flavor=ld.lld",
    "-C", "linker=rust-lld",
]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]